# Generated by Django 6.0.4 on 2026-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dresses/'),
        ),
    ]
