# Generated by Django 6.0.4 on 2026-04-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0004_customer_created_at_customer_notes_dress_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rent_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
