# Generated by Django 6.0.4 on 2026-05-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dresses', '0007_transaction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bust',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='shoulder',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
